# Nom du programme
NAME = FragTrap

# Compilateur et options
CC = c++
CXXFLAGS = -Wall -Werror -Wextra -std=c++98

# Dossiers
SRCDIR =
OBJDIR = obj/
INCDIR =

RESET		=	\033[0m
GREEN		=	\033[32m
YELLOW		=	\033[33m
BLUE		=	\033[34m

# Fichiers sources et objets
SRCS = main.cpp \
		ClapTrap.cpp \
		ScavTrap.cpp \
		FragTrap.cpp \

OBJS = $(SRCS:.cpp=.o)
		
#paths
SRC_PATH =

OBJ_PATH = $(addprefix $(OBJDIR), $(OBJS))

# Compilation du programme
all: $(NAME)
		@printf "$(BLUE)Welcome to EX02 of CPP03\n$(RESET)"

$(NAME): $(OBJ_PATH)
		@echo "$(YELLOW)Compiling [$(NAME)]...$(RESET)"
		@$(CC) $(CXXFLAGS) $(OBJ_PATH) -o $(NAME)
		@echo "$(GREEN)Finished [$(NAME)]$(RESET)"
		

# Compilation des fichiers objets
$(OBJDIR)%.o: %.cpp
	@mkdir -p $(OBJDIR)
	@echo "$(YELLOW)Compiling Contact [$<]...$(RESET)"
	@$(CC) $(CXXFLAGS) -c $< -o $@
	@echo "$(GREEN)Finished [$@]$(RESET)"
	@printf "$(UP)$(CUT)"

# Creation du dossier objets si inexistant
$(OBJDIR):
		@mkdir -p $(OBJDIR)

# Nettoyage des fichiers objets
clean:
	@if [ -d "$(OBJDIR)" ]; then \
	rm -rf $(OBJDIR); \
	echo "$(BLUE)Deleting all objects from /ex02...$(RESET)"; else \
	echo "No objects to remove from /ex02."; \
	fi;

# Nettoyage complet
fclean: clean
	@if [ -f "$(NAME)" ]; then \
	rm -f $(NAME); \
	echo "$(BLUE)Deleting $(NAME) from ex02...$(RESET)"; else \
	echo "No Executable to remove from ex02."; \
	fi;

# Recompiler proprement
re: fclean all

.PHONY: all clean fclean re